### ISSUE TITLE
LoRa-APRS packets need a dest-call that is not 'APRS'

### ISSUE THREAD

**Issue by darksidelemm** [RoelKroes/TBTracker-ESP32#3]
Using a dest call (also called a to-call or an aprs device ID) of 'APRS' means that any software that pull data from the APRS-IS network (e.g. SondeHub) can't tell what software is being used by the tracker.
https://github.com/RoelKroes/TBTracker-ESP32/blob/main/Settings.h#L86

There is information on applying for one of these here: https://github.com/aprsorg/aprs-deviceid/blob/main/ALLOCATING.md
Please apply for one for your software, and use that as the default value. I'd suggest that it shouldn't even be adjustable by the user.

**Comment by RoelKroes** [comment]
I requested a dest-call but after almost 6 weeks it is still not added to the database.

So, I will use the "experimental" ID  **APZTBT** for the time being and add this to the repository outside of the user settings. 

If you have any recommendations, please let me know.
